# Generated by Django 5.1.4 on 2024-12-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_whatsappcontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RECEIVED', 'Received'), ('SEEN', 'Seen')], max_length=50),
        ),
    ]
