# Generated by Django 5.1.4 on 2024-12-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_whatsappmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='message_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
