# Generated by Django 5.1.4 on 2024-12-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_whatsappmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RECEIVED', 'Received'), ('READ', 'Read')], max_length=50),
        ),
    ]
